# Import required classes from PyFlink Table API
# EnvironmentSettings → Used to configure streaming or batch mode
# TableEnvironment → Main entry point to execute SQL and manage tables
from pyflink.table import EnvironmentSettings, TableEnvironment


# -------------------------------
# STEP 1: Create Streaming Environment
# -------------------------------

env_settings = (
    EnvironmentSettings.in_streaming_mode()
)  # tells Flink this is a STREAMING job Because we are consuming continuous real-time events from Kafka.
t_env = TableEnvironment.create(
    env_settings
)  # Think of this as starting the Flink engine. All SQL queries and table definitions will run using this object.


# -------------------------------
# STEP 2: Enable Checkpointing
# -------------------------------

t_env.get_config().set("execution.checkpointing.interval", "10s")


# -------------------------------
# STEP 3: Define Kafka Source Table
# -------------------------------

# We create a Flink table that is backed by a Kafka topic.
# This tells Flink:
#   - Where to read data from
#   - What schema to expect
#   - How to parse incoming messages

t_env.execute_sql(
    """
CREATE TABLE payments_raw (
    transaction_id STRING,   -- Unique payment ID generated by Faker
    bank_code STRING,        -- Bank identifier (HDFC, SBI, etc.)
    amount DOUBLE,           -- Transaction amount
    payment_type STRING,     -- NEFT / IMPS / RTGS
    status STRING,           -- SUCCESS or FAILED
    event_time STRING        -- Event timestamp (currently string)
) WITH (
    'connector' = 'kafka',   -- Use Kafka connector
    'topic' = 'payments_raw',   -- Kafka topic name
    'properties.bootstrap.servers' = 'kafka:9092',  
        -- Kafka service name inside Docker network
        -- NOT localhost (because Flink runs inside container)
    'properties.group.id' = 'flink-consumer-group',
        -- Kafka consumer group ID
        -- Used for offset tracking and parallel processing
    'scan.startup.mode' = 'earliest-offset',
        -- Start reading from beginning of topic (good for testing)
    'format' = 'json'
        -- Our producer sends JSON, so Flink will auto-parse JSON fields
)
"""
)
## Postgres Sink Table Definition
t_env.execute_sql(
    """
CREATE TABLE payments_sink (
 transaction_id STRING,
 bank_code STRING,
 amount DOUBLE,
 payment_type STRING,
 status STRING,
 event_time TIMESTAMP(3)
) WITH (
 'connector' = 'jdbc',
 'url' = 'jdbc:postgresql://postgres:5432/payments',
 'table-name' = 'payments_sink',
 'username' = 'postgres',
 'password' = 'postgres'
)
"""
)

## Postgres Aggregates Table Definition
t_env.execute_sql(
    """
CREATE TABLE payment_aggregates (
    bank_code STRING,
    total_transactions INT,
    failed_transactions INT,
    success_rate DOUBLE,
    window_start TIMESTAMP(3),
    window_end TIMESTAMP(3)
) WITH (
    'connector' = 'jdbc',
    'url' = 'jdbc:postgresql://postgres:5432/payments',
    'table-name' = 'payment_aggregates',
    'username' = 'postgres',
    'password' = 'postgres'
)
"""
)
## Kafka Alerts Table Definition
t_env.execute_sql(
    """
CREATE TABLE payments_alerts (
    bank_code STRING,
    total_transactions INT,
    failed_transactions INT,
    success_rate DOUBLE,
    window_start TIMESTAMP(3),
    window_end TIMESTAMP(3)
) WITH (
    'connector' = 'kafka',
    'topic' = 'payments.alerts',
    'properties.bootstrap.servers' = 'kafka:9092',
    'format' = 'json'
)
"""
)

## Insert into Postgres from Kafka
t_env.execute_sql(
    """
INSERT INTO payments_sink
SELECT
transaction_id,
bank_code,
amount,
payment_type,
status,
CAST(REPLACE(event_time,'T',' ') AS TIMESTAMP)
FROM payments_raw
"""
)


t_env.execute_sql(
    """
INSERT INTO payment_aggregates
SELECT
    bank_code,
    CAST(COUNT(*) AS INT) AS total_transactions,
    CAST(SUM(CASE WHEN status = 'FAILED' THEN 1 ELSE 0 END) AS INT) AS failed_transactions,
    (COUNT(*) - SUM(CASE WHEN status = 'FAILED' THEN 1 ELSE 0 END)) * 1.0 / COUNT(*) AS success_rate,
    TUMBLE_START(proctime(), INTERVAL '1' MINUTE) AS window_start,
    TUMBLE_END(proctime(), INTERVAL '1' MINUTE) AS window_end
FROM payments_raw
GROUP BY
    bank_code,
    TUMBLE(proctime(), INTERVAL '1' MINUTE)
"""
)

t_env.execute_sql(
    """
INSERT INTO payments_alerts
SELECT
bank_code,
CAST(COUNT(*) AS INT) AS total_transactions,
CAST(SUM(CASE WHEN status = 'FAILED' THEN 1 ELSE 0 END) AS INT) AS failed_transactions,
(COUNT(*) - SUM(CASE WHEN status = 'FAILED' THEN 1 ELSE 0 END)) * 1.0 / COUNT(*) AS success_rate,
TUMBLE_START(proctime(), INTERVAL '1' MINUTE) AS window_start,
TUMBLE_END(proctime(), INTERVAL '1' MINUTE) AS window_end
FROM payments_raw
GROUP BY
bank_code,
TUMBLE(proctime(), INTERVAL '1' MINUTE)
HAVING
SUM(CASE WHEN status = 'FAILED' THEN 1 ELSE 0 END) * 1.0 / COUNT(*) > 0.05
"""
)
